name: Dev CI

on:
  push:
    branches: [ "env/devs" ]
  pull_request:
    branches: [ "env/devs" ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install test package
